config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#what_to_see_in_vilnius'

get "what-to-see-in-vilnius",       to: 'pages#what_to_see_in_vilnius'
get "where-to-eat-in-vilnius",      to: 'pages#where_to_eat_in_vilnius'
get "where-to-party-in-vilnius",    to: 'pages#where_to_party_in_vilnius'
get "where-to-stay-in-vilnius",     to: 'pages#where_to_stay_in_vilnius'
get "what-to-listen-in-vilnius",    to: 'pages#what_to_listen_in_vilnius'
get "fun-facts-about-Lithuania",    to: 'pages#fun_facts_about_Lithuania'
get "successful_ebook_purchase",    to: 'pages#successful_ebook_purchase'
get "ebook",                        to: 'pages#ebook'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def ebook
  end

  def what_to_see_in_vilnius
  end

  def where_to_eat_in_vilnius
  end

  def where_to_party_in_vilnius
  end

  def where_to_stay_in_vilnius
  end

  def what_to_listen_in_vilnius
  end

  def fun_facts_about_Lithuania
  end

  def successful_ebook_purchase
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="<%= image_path 'logo-icon' %>" />


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= content_for?(:head) ? yield(:head) : '' %>



  <% if Rails.env.production? %>
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-102213941-1', 'auto');
    </script>
  <% end %>

  </head>
  <body>
  <%= render 'shared/navbar' %>

 <%= yield %>

    <!-- TODO: Here goes your content! -->

<%= render 'shared/footer' %>

    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/pages/contribute.html.erb
     <div class="banner" style="background:url(<%= image_path 'contact' %>); height: auto;">
     <!-- <div class="layer"></div> -->
       <div class="col-md-offset-1 col-md-5">
        <div class="padding-top-152">
        <div class="text-shadow">
          <div class="text-center">
            <h1 class="banner-text"> Have I missed somehitng...?</h1>
          </div>

          <h3 class="text-white">Share your favourite spots in Lithuania. Tell me what does it mean for you to be Lithuanian?</h3>

<!--           <h5 class="padding-top-18 text-white">SIDE NOTE: IT'S NOT YOUR REGULAR TOURIST GUIDE</h5> -->
        </div>
        </div>
      </div>
      </div>

      <div class="color-yellow">
        <div class="container">
          <br>
            <h1 class="text-center padding-top-18">Write a message</h1>
          <br><br>
          <div class="row">
            <div class="col-md-offset-1 col-md-5">
            <br>
              <img src="<%= image_path 'baltijos-kelias' %>" alt="" class="image-card">
                <!-- <div class="layer"></div> -->
            </div>
            <div class="col-md-5">
              <h2>Baltijos Kelias (eng. Baltic way)</h2>
              <p>It was a peaceful political demonstration that occurred on 23 August 1989. Approximately two million people joined their hands to form a human chain spanning 675.5 kilometres (419.7 mi) across the three Baltic states – Estonia, Latvia, and Lithuania. The protest was designed to draw global attention by demonstrating a desire for independence from Soviet Union and illustrated solidarity among the three nation</p>
            </div>
          </div>
          </div>
          </div>

app/views/pages/ebook.html.erb
<% content_for :head do %>

<title>Vilnius City Guide by a Local - Pocket E-Book (pdf)</title>
<meta content="Pocket E-book guide for Vilnius City. Read offline about Vilnius highlights from a local. Click here to get it" name="description">

<meta property="og:title" content="E-Book : Vilnius City Guide"/>
<meta property="og:url" content="http://localvilnius.guide/ebook"/>
<meta property="og:type" content="website"/>
<meta property="og:description" content="Pocket E-book guide for Vilnius City. Read offline about Vilnius highlights from a local. Click here to get it"/>
<meta property="og:image" content="http://localvilnius.guide/assets/ebook-dfabc855b2bd38794cc820d46257b3c8083aabda423ba099dd96644289c2841b.png"/>
<% end %>


<div class="banner" style="background:url(<%= image_path 'vilnius-ebooks' %>);">
  <div class="layer"></div>
  <div class="col-md-offset-1 col-md-5">
    <div class="padding-top-152">
      <div class="text-shadow">
        <div class="inline">
          <img src="<%= image_path 'local_kris.png' %>" alt="" class="foto">
          <h1 class="banner-text"> Vilnius guide by a local</h1>
        </div>

        <h3 class="text-white">What to do, see, eat, drink, night out in Vilnius? Ultimate guide, to make your trip uniquely Lithuanian. </h3>

        <h5 class="padding-top-18 text-white">SIDE NOTE: IT'S NOT YOUR REGULAR TOURIST GUIDE</h5>
      </div>
    </div>
  </div>
</div>

<div class="color-yellow">
  <div class="container">
    <br>
    <h1 class="text-center padding-top-18">Get Full Ultimate Vilnius Guide Book</h1>
    <br><br>

    <div class="row">
      <div class="col-md-offset-1 col-md-5 text-center">
        <img src="<%= image_path 'ebook' %>" alt="" class="img-radius" style="height: 420px;">
      </div>

      <div class="col-md-5">
        <h2>Offline E-book</h2>

        <ul class="font-family-josefin font-size-19"">
          <li>Read guide offline without internet connection on the plane or on the go</li>
          <li>Get additional secret places for eating and sightseeing in Vilnius</li>
          <li>Full sightseeing Vilnius map</li>
          <li>Day plan for a weekend break in Vilnius</li>
          <li>Support this website and editorial work that it takes to keep the guide up to date</li>
        </ul>

        <p>Get your Full Ultimate Vilnius Guide and enjoy reading it without internet at any time on your smart device</p>

        <div style="padding-bottom: 5px;"></div>
        <div class="display-inline">
          <h2 class="ebook-old-price">Price: 9 eur</h2>
          <p style="margin-bottom: -18px;"></p>
          <h2 class="ebook-new-price"> <span style="color: green">New price: </span> 4 eur</h2>

          <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="display-inline" style="padding-left: 80px;">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="EKMGRJTB6C8QG">
            <input type="image" src="https://www.paypalobjects.com/en_US/DK/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
        </div>
      </div>
    </div>
    <br><br><br><br>

  </div>
</div>

app/views/pages/fun_facts_about_Lithuania.html.erb
<% content_for :head do %>
<title>Interesting Facts About Lithuania - Vilnius Guide by a Local</title>
<meta content="Fun facts about Lithuania with useful tips and tricks from a locals for your exciting stay in Vilnius. Click here to read it" name="description">

<meta property="og:title" content="Interesting Facts About Lithuania"/>
<meta property="og:url" content="http://localvilnius.guide/fun-facts-about-Lithuania"/>
<meta property="og:type" content="website"/>
<meta property="og:description" content="Fun facts about Lithuania with useful tips and tricks from a locals for your exciting stay in Vilnius. Click here to read more"/>
<meta property="og:image" content="http://localvilnius.guide/assets/lt-girl-0f9c84af6c9c16e19c561539056bc7c9bbaf11dac6c6896aa06689514c3b1ee2.jpg"/>

<% end %>



     <div class="banner" style="background:url(<%= image_path 'lt-girl' %>);">
     <!-- <div class="layer"></div> -->
       <div class="col-md-offset-1 col-md-5">
        <div class="padding-top-152">
        <div class="text-shadow">
          <div class="inline">
            <img src="<%= image_path 'local_kris.png' %>" alt="" class="foto">
            <h1 class="banner-text"> Vilnius guide by a local</h1>
          </div>

          <h3 class="text-white">What to do, see, eat, drink, night out in Vilnius? Ultimate guide, to make your trip uniquely Lithuanian. </h3>

          <h5 class="padding-top-18 text-white">SIDE NOTE: IT'S NOT YOUR REGULAR TOURIST GUIDE</h5>
        </div>
        </div>
      </div>
      </div>

      <div class="color-yellow">
        <div class="container">
          <br>
            <h1 class="text-center padding-top-18">Fun Facts</h1>
          <br><br>
          <div class="row">
            <div class="col-md-offset-1 col-md-5">
            <br>
              <img src="<%= image_path 'baltijos-kelias' %>" alt="" class="image-card">
                <!-- <div class="layer"></div> -->
            </div>
            <div class="col-md-5">
              <h2>Baltijos Kelias (eng. Baltic way)</h2>
              <p>It was a peaceful political demonstration that occurred on 23 August 1989. Approximately two million people joined their hands to form a human chain spanning 675.5 kilometers (419.7 mi) across the three Baltic States – Estonia, Latvia, and Lithuania. The protest was designed to draw global attention by demonstrating a desire for independence from Soviet Union and illustrated solidarity among the three nations.</p>
            </div>
          </div>
          <br>

          <div class="row">
            <div class="col-md-offset-1 col-md-5">
              <h2>Second religion</h2>
              <p>Basketball is usually called in Lithuania a second religion and it is by far the most popular sport in the country. Popularity of sport grew during Soviet Union oppression as it was seen as a mean to fight for independence. Since then Lithuania became basketball powerhouse in the world with legendary NBA players like Arvydas Sabonis, Šarūnas Marčiulionis and current NBA superstars like Jonas Valančiūnas, Donatas Motiejūnas, Domantas Sabonis among many others.</p>
            </div>
            <div class="col-md-5">
            <br><br>
              <img src="<%= image_path 'basketball' %>" alt="" class="image-card">
                    <!-- <div class="layer"></div> -->
            </div>
          </div>
        <br>

        <div class="row">
          <div class="col-md-offset-1 col-md-5">
          <br><br>
            <img src="<%= image_path 'stork' %>" alt="" class="image-card">
            <!-- <div class="layer"></div> -->
          </div>
          <div class="col-md-5">
            <h2>Gandras (eng. White Stork)</h2>
            <p>Kept as a national bird and as a symbol. Whooping 8% of all white storks in the world breed in Lithuania making it the densest country for this species. This giant bird has somewhat warm and pleasant association to any Lithuanian. You can often see white storks in the countryside walking in the fields or on the rooftops of old houses. And of course, storks bring babies - that's a common knowledge, we all grow up knowing that, so watch out or a baby might fall into your lap.</p>
          </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-offset-1 col-md-5">
              <h2>Folk Dance Festival</h2>
              <p>It does sound a bit lame at first, but actually it is one of the coolest and most unique thing you can see in Lithuania. Every 4 years almost 2000 folk dancers from across Lithuania and abroad gather together to perform traditional folk dances. Every dancer receive special choreography instructions to form well coordinated massive human chains and ever changing shapes while dancing making it one of the kind event in the world. It is a part of UNESCO Intangible Cultural Heritage for a reason... It's just amazing. Upcoming Folk Dance Festival will be in 2020.</p>
            </div>
            <div class="col-md-5">
            <br><br>
              <img src="<%= image_path 'dainu-svente' %>" alt="" class="image-card">
                    <!-- <div class="layer"></div> -->
            </div>
          </div>
        <br>



        <br><br><br><br><br>
        <div class="text-center">
          <img src="<%= image_path 'symb.png' %>" alt="" class="symb"><br><br><br>

          <h1 class="text-center padding-top-18">Tips & Tricks</h1>
        </div>
        <br><br>
        <div class="row">
          <div class="col-md-offset-1 col-md-10">
            <!-- <ul> -->
              <h2>Transportation in Vilnius </h2>
              <p>Most of the places suggested in this guide is within walking distance. However, in case you want to go further away from the city center I would strongly advice to use Uber app. Uber drivers are more likely to speak well in English and you can be worry-free about the rates that you are being charged. Travelers hygiene rule number 1 - if you travel with a taxi, always ask before hand for the price estimation. 1km usually cost around 1-2 eur. Keep 10 - 15 Eur benchmark in mind, as you should be able to reach even the furthest places on this list for the amount. Worth noting that night rates are usually much higher so don't be surprised if you pay more coming out of the bar. Travelers hygiene rule number 2 - never take taxi straight from the airport, railway or bus station as you are sure that you will over pay. </p>

              <br>
              <h2>Transportation from Vilnius airport </h2>
              <p>There are three options that you could take - taxi (Uber), bus, train. Bus would be the cheapest option. My recommendation is to take Uber for the most convenience.</p>

              <br>
              <h2>Cheap flight tickets to Lithuania </h2>
              <p>You can get very cheap tickets to Kaunas since Ryanair has a service center there for their planes. It is not uncommon to find a ticket from Copenhagen to Kaunas for 20 Eur. Kaunas is the second largest city in Lithuania and it is 100km away from Vilnius. Once you are in Kaunas airport you can take a taxi (Uber) to train station and get comfy train ride to Vilnius.</p>

              <br>
              <h2>Caution: Lithuanians speak Lithuanian</h2>
              <p>Lithuanians get very offensive if you call them Russians or think that Lithuanians speak Russian as a mother tongue. We tend to label that person in our minds as a blithering idiot and end conversation at the earliest convenience.</p>
          </div>
        </div>

        <br><br><br><br><br>
        <div class="text-center">
          <img src="<%= image_path 'symb.png' %>" alt="" class="symb"><br><br><br>

          <h1 class="text-center padding-top-18">Few Lithuanian Words</h1>
        </div>
        <br><br>
        <div class="row">
          <div class="col-md-offset-1 col-md-10">
            <ul>
              <li><p><strong>Ačiū</strong>- Thank you. If you want to make correct pronunciation imagine that you are sneezing with a long aaaciu (nose cleaning is not required afterwards)</p></li>
              <li><p><strong>Į sveikatą </strong>- Cheers</p></li>
              <li><p><strong>Labas </strong>- Hey</p></li>
              <li><p><strong>Mano vardas (Your name here)</strong>- My name is (Your name here)</p></li>
              <li><p><strong>Kiek kainuoja? </strong>- How much?</p></li>
              <li><p><strong>Taip </strong>- Yes</p></li>
              <li><p><strong>Ne </strong>- No</p></li>
              <li><p><strong>Man Patinka Lietuva </strong>- I like Lithuania</p></li>
              <li><p><strong>Tu man patinki </strong>- I like you</p></li>
            </ul>
          </div>
        </div>


<!-- <br><br><br><br><br>
            <div class="text-center">
            <img src="<%#= image_path 'symb.png' %>" alt="" class="symb"><br><br><br>
                <h1 class="text-center padding-top-18">Brief Lithuanian History</h1>
            </div>

          <br><br><br><br>
        <div class="row">
          <div class="col-md-offset-1 col-md-10">
      <p>To be written...</p>

          </div>
        </div> -->

        <br><br><br><br>
<div class="text-center">
        <%= link_to "What to see in Vilnius >>", what_to_see_in_vilnius_path , class:"btn btn-default bottom-button", style: ""%>
        <br><br><br><br>
</div>
  </div>
</div>

app/views/pages/successful_ebook_purchase.html.erb
<META NAME="robots" CONTENT="noindex,nofollow">


<div class="banner" style="background:url(<%= image_path 'success' %>);">
  <div class="col-md-offset-7 col-md-3 text-center">
    <div style="margin-top: 395px;">
      <div class="success-div">
        <a class="nav-contr btn btn-success success-text" href="/assets/ultimate-vilnius-guide.pdf">Download your E-book</a>
        <p class="">if you have dificulties downloading or something is not working, please contact me: kristijonas.zibutis@gmail.com or fb: Kristijonas Zibutis</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/what_to_see_in_vilnius.html.erb
<% content_for :head do %>

<title>What to see in Vilnius - Vilnius Guide by a Local</title>
<meta content="Famous Vilnius places to see and local things to do while you are on your holiday trip in Vilnius. Click to get Vilnius city guide" name="description">

<meta property="og:title" content="Vilnius Guide by a Local"/>
<meta property="og:url" content="http://localvilnius.guide/what-to-see-in-vilnius"/>
<meta property="og:type" content="website"/>
<meta property="og:description" content="Famous Vilnius places to see and local things to do while you are on your holidays in Vilnius. Click to get Vilnius city guide"/>
<meta property="og:image" content="http://localvilnius.guide/assets/fb-landing-photo-cd9225e1fda38ba3f9dd5f657c3d6c867750047147caa0b29d5944fdcbe4ed26.png"/>
<% end %>

     <div class="banner" style="background:url(<%= image_path 'Lietuva4.jpg' %>);">
     <!-- <div class="layer"></div> -->
       <div class="col-md-offset-1 col-md-5">
        <div class="padding-top-152">
        <div class="text-shadow">
          <div class="inline">
            <img src="<%= image_path 'local_kris.png' %>" alt="" class="foto">
            <h1 class="banner-text"> Vilnius guide by a local</h1>
          </div>

          <h3 class="text-white">What to do, see, eat, drink, night out in Vilnius? Ultimate guide, to make your trip uniquely Lithuanian. </h3>

          <h5 class="padding-top-18 text-white">SIDE NOTE: IT'S NOT YOUR REGULAR TOURIST GUIDE</h5>
        </div>
        </div>
      </div>
      </div>

      <div class="color-yellow">
        <div class="container">
          <br>
            <h1 class="text-center padding-top-18">What to see in Vilnius</h1>
          <br><br>
          <div class="row">
            <div class="col-md-offset-1 col-md-5">
              <img src="<%= image_path 'gedimino-pilis' %>" alt="" class="image-card">
                <!-- <div class="layer"></div> -->
            </div>
            <div class="col-md-5">
                            <h2>Gedimino Castle</h2>
              <p>It's a Castle, really... it might look like the only defense tower that's left after destruction, but it's actually a Castle. Ask any local person... Go on top of the mountain and from there you can see some amazing views. By the side of the castle you will find the hill of three crosses. I wouldn't advise going there - seeing from a distance should be enough.</p>
              <h5>Address: Gedimino Castle</h5>
            </div>
          </div>
          <br>

          <div class="row">
            <div class="col-md-offset-1 col-md-5">
              <h2>Vilnius old town</h2>
              <p>Hit Pilies street which is one of the oldest streets in the city. Put your adventurous explorers goggles on and get lost in narrow side streets, green inner house gardens to discover cozy Vilnius old town on your own terms.</p>
              <h5>Address: Pilies street</h5>
            </div>
            <div class="col-md-5">
              <img src="<%= image_path 'senamiestis' %>" alt="" class="image-card">
                    <!-- <div class="layer"></div> -->
            </div>
          </div>
        <br>

        <div class="row">
          <div class="col-md-offset-1 col-md-5">
            <img src="<%= image_path 'uzupis' %>" alt="" class="image-card">
            <!-- <div class="layer"></div> -->
          </div>
          <div class="col-md-5">
            <h2>Republic of Užupis</h2>
            <p>Area of Vilnius for arty bohemian people. Stop by the main sculpture on the main square to read Constitution of Uzupis which is a funny read in itself - rule #1 - "People have the right to live by the River Vilnelė, while the River Vilnelė has the right to flow past people.", #12  "A dog has the right to be a dog." and #37 "People have the right to have no rights.". Explore the area and stop by local artist galleries and small boutiques.</p>
            <h5>Address place: Užupio street </h5>
          </div>
        </div>
        <br>

      <div class="row">
        <div class="col-md-offset-1 col-md-5">
          <h2>Cathedral</h2>
          <p>The biggest, baddest and the meanest church in Lithuania - the cathedral. It's worth swinging by as it is conveniently situated between all the sightseeing places. You can also get a ticket to the underground tombs if you into Lara Croft type of explorations.
</p>
          <h5>Address: Šventaragio street </h5>
        </div>
        <div class="col-md-5">
          <img src="<%= image_path 'katedra' %>" alt="" class="image-card">
          <!-- <div class="layer"></div> -->
        </div>
      </div>
<br>
        <div class="row">
          <div class="col-md-offset-1 col-md-5">
            <img src="<%= image_path 'ausros-vartai' %>" alt="" class="image-card">
            <!-- <div class="layer"></div> -->
          </div>
          <div class="col-md-5">
            <h2>Gates of Dawn</h2>
            <p>As it was quite trendy to build walls back in 15 centaury we build one too to protect Vilnius citizens from Tatars. Gates of Dawn was the main entry point and now it is the biggest tourist attraction with historical and religious significance. Above the gates you can see sacred and very rare version of Madona painting without a baby. It is not known who is the author of the painting but it is believed that it has magical powers.
 </p>
            <h5>Address: Aušros Vartų street 14</h5>
          </div>
        </div>
        <br>
              <div class="row">
        <div class="col-md-offset-1 col-md-5">
          <h2>TV Tower</h2>
          <p>Highly recommendable when you have more than just a few days, as it will also get you to a district outside of the city center. Real gem for those who want to see communistic block houses and all the other ‘beauty’ that Soviet Union has left behind.</p>
          <h5>Address: Sausio 13-osios street 10 </h5>
        </div>
        <div class="col-md-5">
          <img src="<%= image_path 'televizijos-bokstas' %>" alt="" class="image-card">
          <!-- <div class="layer"></div> -->
        </div>
      </div>
      <br>


        <div class="row">
          <div class="col-md-offset-1 col-md-5">
            <img src="<%= image_path 'Vilnius-Panorama' %>" alt="" class="image-card">
            <!-- <div class="layer"></div> -->
          </div>
          <div class="col-md-5">
            <h2>Gedimino Avenue & Konstitucijos street</h2>
            <p>Gedimino prospektas - the main street of the city and it represents modern Vilnius. If you go down Gedimino Avenue and then turn towards Baltasis Tiltas, you will reach commercial district in Konstitucijos Street with its highrises at the other side of the river. With numerous foreign companies outsourcing their IT departments to Lithuania, this area became vibrant economic center of a capital city.</p>
            <h5>Address: Gedimino Avenue & Konstitucijos street </h5>
          </div>
        </div>
        <br>
      <div class="row">
        <div class="col-md-offset-1 col-md-5">
          <h2>Barbakanas</h2>
          <p>Beautiful and quite secret place (non touristic) to see night panorama of Vilnius. You would need to go the bastion of Vilnius city wall down the Subacius street and then follow the path over the park down to Maironio street. Don’t get surprised to see local lovers on the way enjoying their time as well.
          <h5>Address: Konstitucijos Avenue 20</h5>
        </div>
        <div class="col-md-5">
          <img src="<%= image_path 'barbakanas' %>" alt="" class="image-card">
          <!-- <div class="layer"></div> -->
        </div>
      </div>
<br>
        <div class="row">
          <div class="col-md-offset-1 col-md-5">
            <img src="<%= image_path 'onos-baznycia' %>" alt="" class="image-card">
            <!-- <div class="layer"></div> -->
          </div>
          <div class="col-md-5">
            <h2>St. Annes church</h2>
          <p>Said to be one of the nicest in Lithuania. Rumor has it that Napoleon wanted to take it back home on the palm of his hand. It's also pretty small, so makes sense.
</p>
          <h5>Address: Maironio street 8 </h5>

          </div>
        </div>
<br>
        <div class="row">
          <div class="col-md-offset-1 col-md-5">
          <h2>Belmontas</h2>
          <p>Beautiful Lithuanian vintage style restaurant complex located in a regional park. Among meticulously maintained gardens you can also find a waterfall so bring your swim gear if you want to dip in and cool down jumping from a cliff. Definitely one of the must go places if you have a bit more time in Vilnius as it is slightly further from the city center.
</p>
          <h5>Address: Belmonto street 17 </h5>
        </div>
        <div class="col-md-5">
          <img src="<%= image_path 'Belmontas' %>" alt="" class="image-card">
          <!-- <div class="layer"></div> -->
        </div>
      </div>

<br><br><br><br><br>
            <div class="text-center">
            <img src="<%= image_path 'symb.png' %>" alt="" class="symb"><br><br><br>
<!--                 <h1 class="text-center padding-top-18">Good restaurants in Vilnius</h1> -->
            </div>

          <br><br><br><br>
        <div class="row">
          <div class="col-md-offset-1 col-md-10">
            <img src="<%= image_path 'vamzdis' %>" alt="" class="img-radius" style="width: 100%;">
            <!-- <div class="layer"></div> -->
<!--           </div>
          <div class="col-md-5"> -->
            <h2>The Pipe</h2>
            <p>I don't even know where to start with this one... Let's first address all the elephants in the room - yes, it's an art peace that Vilius bought for a hefty sum of money. No, it's not an actual pipe. Yes, it has been standing there for quite a while now and it seems it will stay for a bit longer. It's one of the most controversial objects in Vilnius city center and brings a lot of negative reflections from locals. If you like to learn some new Lithuanian words just ask any passer by what do they think about the Pipe?</p>
            <h5>Address: Žvejų street 14 </h5>
          </div>
        </div>



        <br><br><br><br>
<div class="text-center">
        <%= link_to "Where to night out in Vilnius >>", where_to_party_in_vilnius_path , class:"btn btn-default bottom-button", style: ""%>
        <br><br><br><br>
</div>
  </div>
</div>